/**
 * Implementation of hook_views_api().
 */
function pft_views_api() {
  return array(
    'api' => 2,
    //'path' => drupal_get_path('module', 'pft'),
    'path' => drupal_get_path('module', 'pft') . '/includes',
  );
}

pft_imagecache_default_presets() {
  $presets = array();
  $presets['diagram_large'] = array (
    'presetname' => 'diagram_large',
    'actions' => 
    array (
      0 => 
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => 
        array (
          'width' => '1024',
          'height' => '',
          'upscale' => 0,
        ),
      ),
    ),
  );
  $presets['diagram_medium'] = array (
    'presetname' => 'diagram_medium',
    'actions' => 
    array (
      0 => 
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => 
        array (
          'width' => '500',
          'height' => '',
          'upscale' => 1,
        ),
      ),
    ),
  );
  $presets = array();
    $presets['diagram_thumbnail'] = array (
    'presetname' => 'diagram_thumbnail',
    'actions' => 
    array (
      0 => 
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => 
        array (
          'width' => '150',
          'height' => '',
          'upscale' => 0,
        ),
      ),
    ),
  );
}
