<?php
/**
 * @file
 *
 *
 * sturnbull
 *
 * Created 18 Jun 2010
 */

final class ProfileGenerator {
  const PERM = 'generate installation profile';
  const URL = 'admin/settings/profile-generator';

  const DEFAULT_NAME = 'shuri';
  const DEFAULT_TITLE = 'Sheffield Hallam University - Research Institute';
  const DEFAULT_DESCRIPTION = 'Installation profile generated automatically on !date';

  const PLUGIN = 'profile_element';
  const PLUGIN_DIR = 'plugins/';
  const PLUGIN_FORM_CALLBACK = 'form callback';
  const PLUGIN_GENERATE_CALLBACK = 'generate callback';

  static public function make_function($plugin, $root) {
    return "{$plugin['plugin module']}_{$plugin['plugin type']}_{$plugin['name']}_{$root}";
  }
}


/**
 * Implementation of hook_ctools_plugin_directory()
 */
function profile_generator_ctools_plugin_directory($module, $plugin) {
  if ($module == 'profile_generator' && $plugin == ProfileGenerator::PLUGIN) {
    return ProfileGenerator::PLUGIN_DIR . ProfileGenerator::PLUGIN;
  }
}


/**
 * Implementation of hook_perm()
 */
function profile_generator_perm() {
  return array(ProfileGenerator::PERM);
}

/**
 * Implementation of hook_menu();
 */
function profile_generator_menu() {
  $items = array();
  $items[ProfileGenerator::URL] = array(
      'title' => t('Generate installation profile'),
      'description' => t('Generate a Drupal installation profile'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('profile_generator_form'),
      'access arguments' => array(ProfileGenerator::PERM),
      'file' => 'profile_generator.form.inc',
      'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Implementation of hook_theme().
 */
function profile_generator_theme() {
  return array(
    'profile_generator_function' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_variable' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_db_insert' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_db_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_db_truncate_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_command' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_commands' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_task' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_php' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'profile_generator_export' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
    'install_profile_api' => array(
      'arguments' => array('element' => NULL),
      'file' => 'profile_generator.themes.inc',
    ),
  );
}


/**
 * Implementation of hook_elements().
 */
function profile_generator_elements() {
  return array(
    'profile_generator_function' => array(
      '#input' => TRUE,
    ),
    'profile_generator_variable' => array(
      '#input' => TRUE,
    ),
    'profile_generator_db_insert' => array(
      '#input' => TRUE,
      '#suffix' => ";\n",
    ),
    'profile_generator_db_table' => array(
      '#input' => TRUE,
      '#suffix' => ";\n",
    ),
    'profile_generator_db_truncate_table' => array(
      '#input' => TRUE,
      '#suffix' => ";\n",
    ),
    'profile_generator_command' => array(
      '#input' => TRUE,
      '#suffix' => ";\n",
    ),
    'profile_generator_commands' => array(
      '#input' => TRUE,
      '#suffix' => ";\n",
    ),
    'profile_generator_task' => array(
      '#input' => TRUE,
      '#prefix' => "\n",
      '#suffix' => "\n",
    ),
    'profile_generator_php' => array(
      '#input' => TRUE,
      '#prefix' => "\n",
      '#suffix' => "\n",
    ),
    'profile_generator_export' => array(
      '#input' => TRUE,
      '#prefix' => "\n",
      '#suffix' => "\n",
    ),
    'install_profile_api' => array(
      '#input' => TRUE,
      '#suffix' => ";\n",
    ),
  );
}

function sprintf_placeholders(&$arguments = array()) {
  if (!is_array($arguments)) {
    $arguments = array($arguments);
  }
  $placeholders = array();
  foreach ($arguments as &$argument) {
    $placeholders[] = sprintf_type_placeholder($argument);
  }
  return implode(', ', $placeholders);
}

function sprintf_type_placeholder(&$argument) {
  if (is_string($argument)) {
    $ch = substr($argument, 0, 1);
    if ($ch!='$' && $ch!='^') {
      $argument = sprintf_var_export($argument);
    }
    if ($ch=='^') {
      $argument = substr($argument, 1);
    }
    $placeholder = '%s';
  }
  elseif (is_bool($argument)) {
    $argument = $argument ? 'TRUE' : 'FALSE';
    $placeholder = '%s';
  }
  elseif (is_float($argument)) {
    $argument = sprintf_var_export($argument);
    $placeholder = '%f';
  }
  elseif (is_integer($argument)) {
    $argument = sprintf_var_export($argument);
    $placeholder = '%d';
  }
  elseif (is_null($argument)) {
    $argument = sprintf_var_export(0);
    $placeholder = '%d';
  }
  else {
    $argument = sprintf_var_export((array) $argument);
    $placeholder = '%s';
  }
  return $placeholder;
}

function sprintf_var_export($var) {
  return preg_replace('/\s+/', ' ', var_export($var, TRUE));
}

