; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.19"

; Modules

projects[install_profile_api] = 2.1

projects[admin_menu][version] = "1.6"

projects[adminrole][version] = "1.3"

projects[advanced_help][version] = "1.2"

projects[colorbox][version] = "1.0-beta7"

projects[ctools][version] = "1.8"

projects[date][subdir] = "date"
projects[date][version] = "2.6"

projects[devel][version] = "1.22"

projects[diff][version] = "2.1"

projects[features][version] = "1.0"

projects[filefield][version] = "3.7"

projects[filefield_sources][version] = "1.2"

projects[globalredirect][version] = "1.2"

projects[imageapi][version] = "1.9"

projects[imagecache][version] = "2.0-beta10"

projects[imagefield][version] = "3.7"

projects[jquery_ui][version] = "1.4"

projects[jquery_update][version] = "2.0-alpha1"

projects[login_destination][version] = "2.12"

projects[nodereference_url][version] = "1.6"

projects[og][version] = "2.1"

projects[panels][version] = "3.8"

projects[panels_everywhere][version] = "1.1"

projects[panels_tabs][version] = "1.0-rc6"

projects[pathauto][version] = "1.5"

projects[pft_manage_biz_stories][subdir] = "custom/features"
projects[pft_manage_biz_stories][version] = "1.0-alpha1"

projects[pft_manage_prj_and_us][subdir] = "custom/features"
projects[pft_manage_prj_and_us][version] = "1.0-alpha1"

projects[pft_manage_prj_issues][subdir] = "custom/features"
projects[pft_manage_prj_issues][version] = "1.0-alpha1"

projects[pft_manage_roles][subdir] = "custom/features"
projects[pft_manage_roles][version] = "1.0-alpha1"

projects[profile_generator][version] = "2.1-rc1"

projects[strongarm][version] = "2.0"

projects[tabs][version] = "1.x-dev"

projects[token][version] = "1.15"

projects[vertical_tabs][version] = "1.0-rc1"

projects[views][version] = "2.11"

projects[views_attach][version] = "2.2"

projects[views_bulk_operations][version] = "1.10"

; Themes
projects[precision][version] = "1.0-alpha1"

