<?php
// $Id: $

/**
 * @file
 *
 * PFT Panels Everywhere UI Module
 * Support for Panels Everywhere UI implementation for Project Flow & Tracker
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function pft_basic_ctools_plugin_api($module, $api) {
  /***
  if ($module == 'strongarm' && $api == 'strongarm') {
    return array('version' => 1);
  }
  if ($module == 'panels' && $api == 'pipelines') {
    return array('version' => 1);
  }
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
  ***/
}
